---
## /* vim: set tabstop=2 softtabstop=2 shiftwidth=2 expandtab smarttab autoindent: */

- name: "Check if blackbox is installed"
  ansible.builtin.shell:
    cmd: "PATH=\"${PATH}:/usr/local/bin\" which 'blackbox_initialize'"
    executable: "/bin/bash"
  register: "blackbox_init_exe"
  failed_when: false
  changed_when: false

- name: "Install the package"
  ansible.builtin.include_tasks: "install.yml"
  when:
  - "blackbox_force_build or blackbox_init_exe.rc"
