---
## /* vim: set tabstop=2 softtabstop=2 shiftwidth=2 expandtab smarttab autoindent: */
- name: "Converge"
  hosts: "all"
  tasks:
  - name: "Include mireiawen.blackbox"
    include_role:
      name: "mireiawen.blackbox"
