---
## /* vim: set tabstop=2 softtabstop=2 shiftwidth=2 expandtab smarttab autoindent: */

- name: 'Verify'
  hosts: 'all'
  tasks:
  - name: 'Make sure blackbox is installed'
    ansible.builtin.command: 'which blackbox_initialize'
    register: 'result'
    changed_when: false
  - name: 'Check the install result'
    ansible.builtin.assert:
      that: 'result is succeeded'
